# conda env create -f environment.yml
name: sc_surrogate
channels:
  - conda-forge
dependencies:
  - numpy>=1.24.0
  - scipy
  - h5py>=3.10.0
  - scikit-learn>=1.3.0
  - joblib>=1.3.0
  - pyyaml>=6.0
  - pytorch>=2.1.0
  - matplotlib
  - tqdm
  - distgen
  - pytest
  - pip
  - pip:
    - juliacall